// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApi.Data;

namespace ToDoApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ToDoApi.Models.Statu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("ToDoApi.Models.SubToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("StatuId");

                    b.Property<int>("ToDoId");

                    b.HasKey("Id");

                    b.HasIndex("StatuId");

                    b.HasIndex("ToDoId");

                    b.ToTable("SubToDos");
                });

            modelBuilder.Entity("ToDoApi.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("StatuId");

                    b.HasKey("Id");

                    b.HasIndex("StatuId");

                    b.ToTable("ToDos");
                });

            modelBuilder.Entity("ToDoApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToDoApi.Models.SubToDo", b =>
                {
                    b.HasOne("ToDoApi.Models.Statu", "Statu")
                        .WithMany("SubToDo")
                        .HasForeignKey("StatuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ToDoApi.Models.ToDo", "ToDo")
                        .WithMany("SubToDo")
                        .HasForeignKey("ToDoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ToDoApi.Models.ToDo", b =>
                {
                    b.HasOne("ToDoApi.Models.Statu", "Statu")
                        .WithMany("ToDo")
                        .HasForeignKey("StatuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
